### ISSUE TITLE
Cannot find the path specified

### ISSUE THREAD

**Issue by stupe** [hayleox/craftboot#3]
I am using CraftBoot v4.2.3. When I launch the game I have no issues, but when my wife tries she gets this error.
![error](https://cloud.githubusercontent.com/assets/7264030/2748687/59a65b5e-c7d0-11e3-9553-814d63b1d2da.png)

Here is the full error:

```
To report this error, please provide:

java.io.FileNotFoundException: .\instances\modpack\manifest.json (The system cannot find the path specified)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(Unknown Source)
    at java.io.FileOutputStream.<init>(Unknown Source)
    at com.skcraft.launcher.util.HttpRequest$BufferedResponse.saveContent(HttpRequest.java:495)
    at com.skcraft.launcher.update.BaseUpdater.installPackage(BaseUpdater.java:84)
    at com.skcraft.launcher.update.Updater.update(Updater.java:138)
    at com.skcraft.launcher.update.Updater.call(Updater.java:92)
    at com.skcraft.launcher.update.Updater.call(Updater.java:38)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
```

A friend of mine also tried and had no problem installing the mod pack. Any idea whats wrong?

**Comment by hayleox** [comment]
Hmm, are you definitely running the jar for craftboot, and not craftboot-launcher?

**Comment by stupe** [comment]
Yes. She is using the exact same thing I am. I even deleted the instance folder on my computer to see if I could duplicate the problem but couldn't. It will create the folders for me but not for her.

**Comment by hayleox** [comment]
Yeah I realized two seconds too late that she has to be using CraftBoot if you got that far.

Hmm, is this like a work computer or something, where she wouldn't have full write permissions everywhere? If you try manually going to the .craftboot/instances/modpack folder on her computer, are you able to manually create a file called manifest.json?

**Comment by stupe** [comment]
I can manually create the folders, but nothing else, which is odd.

I changed the permissions for her user account and it's working fine now. Not sure why she didn't have them in the first place.

Thanks for the help!

**Comment by hayleox** [comment]
No prob, glad you got it working!

**Comment by jtrent238** [comment]
There May Be Something "Blocking" The Download Of mainfest.json. I Think That Is With My Sister Any Way With Some Of The Mods.
